# Generated by Django 3.1.6 on 2021-03-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storey_range', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resale_prices', models.IntegerField()),
                ('remaining_lease', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('block_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blockaddress')),
                ('flat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flattype')),
                ('level_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leveltype')),
            ],
        ),
        migrations.AddField(
            model_name='blockaddress',
            name='town_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.town'),
        ),
    ]
