# Generated by Django 3.1.6 on 2021-03-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAddress',
            fields=[
                ('id', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('coordinate', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('no_of_rooms', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LevelType',
            fields=[
                ('storey_range', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
                ('resale_prices', models.IntegerField(max_length=32)),
                ('remaining_lease', models.CharField(max_length=255)),
                ('block_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blockaddress')),
                ('flat_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flattype')),
                ('level_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leveltype')),
                ('town_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.town')),
            ],
        ),
        migrations.AddField(
            model_name='blockaddress',
            name='town_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.town'),
        ),
    ]
