# Generated by Django 3.1.6 on 2021-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210304_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resale_prices',
            field=models.FloatField(),
        ),
    ]
